-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: 'v0.11.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: yapf
-   repo: git://github.com/a-sk/mirrors-isort
    sha: 'HEAD'  # Use the sha / tag you want to point at
    hooks:
    -   id: isort